{
  parserClass="plus.tsonlang.TsonParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
  psiClassPrefix="Tson"
  psiImplClassSuffix="Impl"
  psiPackage="plus.tsonlang.psi"
  psiImplPackage="plus.tsonlang.psi.impl"

  elementTypeHolderClass="plus.tsonlang.psi.TsonTypes"
  elementTypeClass="plus.tsonlang.TsonElement"
  tokenTypeClass="plus.tsonlang.TsonElToken"
}

tsonFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY